set-option -g history-limit 9999
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -g default-terminal "screen-256color"
set-option -g default-command bash
unbind C-b
unbind '"'
unbind %
unbind h
unbind v
unbind r
unbind Enter
unbind IC
unbind DC
bind h split-window -h
bind v split-window -v
bind r source-file ~/.tmux.conf
bind IC paste-buffer
bind DC copy-mode
set -s set-clipboard on
set-option -g prefix C-Space
bind-key C-Space send-prefix
