set-option -g history-limit 9999
set -g mouse on
set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g default-terminal "tmux-256color"
set-option -g default-command bash
unbind C-b
unbind '"'
unbind %
unbind h
unbind v
unbind r
unbind Enter
unbind IC
unbind DC
bind h split-window -h
bind v split-window -v
bind r source-file ~/.tmux.conf \; display "CONFIGURATION RELOADED"
bind IC paste-buffer
bind DC copy-mode
set -s set-clipboard on
set-option -g prefix C-a
bind-key C-a send-prefix
set-option -g display-time 5000
set -sg escape-time 100
set -g status-style '#{?client_prefix,bg=cyan,bg=green fg=black}'
set -g status-interval 5
